[C++23] Add missing C++23 headers
Add stdlib.h to fix C++23 build errors because C++23 removed certain
transitive includes

Errors:
frameworks/libs/native_bridge_support/android_api/libc/proxy/trampolines_arm64_to_x86_64-inl.h:48:113:
error: use of undeclared identifier 'aligned_alloc'
   48 | {"native_bridge_aligned_alloc", GetTrampolineFunc<auto(uint64_t,
uint64_t) -> void*>(), reinterpret_cast<void*>(aligned_alloc)},
      |
^~~~~~~~~~~~~

frameworks/libs/native_bridge_support/android_api/libc/proxy/trampolines_arm64_to_x86_64-inl.h:50:92:
error: use of undeclared identifier 'exit'; did you mean '_exit'?
   50 | {"native_bridge_exit", GetTrampolineFunc<auto(int32_t) ->
void>(), reinterpret_cast<void*>(exit)},

frameworks/libs/native_bridge_support/android_api/libc/proxy/libc_translation.cc:41:
frameworks/libs/native_bridge_support/android_api/libc/proxy/trampolines_arm64_to_x86_64-inl.h:61:123:
error: use of undeclared identifier 'posix_memalign'
   61 | {"native_bridge_posix_memalign", GetTrampolineFunc<auto(void*,
uint64_t, uint64_t) -> int32_t>(),
reinterpret_cast<void*>(posix_memalign)},

Generated by Gemini.

Flag: EXEMPT PURE_REFACTOR
Bug: 429048222
Test: m libndk_translation_proxy_libc
Change-Id: I0e2b6b42f6fcacadab00e86c171153a034da15d7